name: 'release'
on: # rebuild any PRs and main branch changes
#   pull_request:
#   push:
#     branches:
#       - main
#       - 'releases/*'
#   workflow_dispatch:
  release:

jobs:
#   build: # make sure build/ci work properly
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: |
#           npm install
#       - run: |
#           npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running action
        uses: actions-on-packages/package-action@ruchika-jain/add-path-input
#         uses: actions-on-packages/package-action@test-action
#         with:
#           path: 'dist'
